# Generated by Django 5.0.7 on 2024-07-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='account_id',
        ),
    ]
